services:
  web:
    build: .
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      #  - .:/app # Mount current directory to /app in the container
      - djb_vol1:/app/data

    ports:
      - "8000:8000"
    env_file: 
      - .env

    environment:
      - PYTHONUNBUFFERED=1 # Ensures Python output is sent straight to the terminal

    networks:
      - sbc_network

networks:
  sbc_network:

volumes:
  djb_vol1: