services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app # Mount current directory to /app in the container
    ports:
      - "8000:8000"
    env_file: 
      - .env

    environment:
      - PYTHONUNBUFFERED=1 # Ensures Python output is sent straight to the terminal
      #- DJANGO_SETTINGS_MODULE=your_project_name.settings # Replace 'your_project_name'
    # If you need a database, uncomment and configure the following:
    # depends_on:
    #   - db
  # db:
  #   image: postgres:15
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_DB=your_db_name
  #     - POSTGRES_USER=your_db_user
  #     - POSTGRES_PASSWORD=your_db_password

# Optional: Define a named volume for database persistence
# volumes:
#   postgres_data: