[project]
name = "django-base"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.1",
    "django-allauth>=65.8.0",
    "pyjwt>2.0",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
]
